apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-boot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-boot
  template:
    metadata:
      labels:
        app: hello-spring-boot
    spec:
      containers:
      - name: hello-spring-boot
        image: agsvp/hello-spring-boot:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
