apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-boot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-boot
  template:
    metadata:
      labels:
        app: hello-spring-boot
    spec:
      containers:
        - name: hello-spring-boot
          image: agsvp/hello-spring-boot:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-spring-boot-service
spec:
  type: NodePort
  selector:
    app: hello-spring-boot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
