name: CI for Spring Boot App  # 1️ Workflow name

on:
  push:
    branches: [master]          # 2️ Trigger: when you push to 'main' branch

env:                          # 3️ Set environment variables
  DOCKER_IMAGE: agsvp/hello-spring-boot:latest

jobs:
  build-and-push:             # 4️ Job name (can be any name)
    runs-on: ubuntu-latest    # 5️ Runner OS: Ubuntu VM provided by GitHub

    steps:
      - name: Checkout code   # 6️ Step 1: Checkout your code
        uses: actions/checkout@v3

      - name: Set up Docker   # 7️ Step 2: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub # 8️ Step 3: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image  # 9️ Step 4: Build & push
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
