name: CI-CD for Spring Boot App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: false
        default: "development"
        type: choice
        options:
          - development
          - uat

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run Tests
        run: ./mvnw test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    env:
      IMAGE_NAME: hello-spring-boot
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      ENV_FILE: ${{ github.event.inputs.environment }}.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy with kubectl
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl apply -f k8s/$ENV_FILE
          kubectl set image deployment/hello-spring-boot-deployment hello-spring-boot=$DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}
