name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - uat

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t <your-dockerhub-username>/hello-spring-boot:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push <your-dockerhub-username>/hello-spring-boot:latest

      - name: Deploy to Kubernetes (Minikube)
        run: |
          kubectl apply -f k8s/${{ github.event.inputs.environment }}.yml
